# Generated by Django 4.0.4 on 2022-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tel_1', models.IntegerField()),
                ('tel_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nbr_etoile', models.PositiveIntegerField()),
            ],
        ),
    ]
