# Generated by Django 4.0.4 on 2022-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
