# Generated by Django 4.0.4 on 2022-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update_on',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
