# Generated by Django 4.0.4 on 2022-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Carte de Crédit'), ('MOMO', 'Mobile Money'), ('P', 'Paypal')], default='CC', max_length=200),
        ),
    ]
