# Generated by Django 4.0.4 on 2022-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
