# Generated by Django 4.0.4 on 2022-07-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_number',
        ),
    ]
