# Generated by Django 4.0.4 on 2022-08-23 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_chambre',
            name='image',
            field=models.ImageField(upload_to='images/chambre', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
    ]
