# Generated by Django 4.0.4 on 2022-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_reservation_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
