# Generated by Django 4.0.4 on 2022-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_image_chambre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_chambre',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='image_hotel',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
