# Generated by Django 4.0.4 on 2022-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
