# Generated by Django 4.0.4 on 2022-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_chambre_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
