# Generated by Django 4.0.4 on 2022-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_reservation_amount_reservation_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payement',
            name='montant',
        ),
        migrations.AddField(
            model_name='payement',
            name='add_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='overnight',
            field=models.PositiveIntegerField(),
        ),
    ]
