# Generated by Django 4.0.4 on 2022-06-26 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_chambre_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='nbr_bed',
            new_name='beds',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.chambre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
