# Generated by Django 4.0.4 on 2022-08-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_image_chambre_token_image_hotel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement_hotel',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
