# Generated by Django 4.0.4 on 2022-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_chambre_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_hotel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
