# Generated by Django 4.0.4 on 2022-06-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_nbr_bed_chambre_beds_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='created_at',
            new_name='add_at',
        ),
    ]
