# Generated by Django 4.0.4 on 2022-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_image_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='tel_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
