# Generated by Django 4.0.4 on 2022-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_reservation_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
