# Generated by Django 4.0.4 on 2022-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_created_at_equipement_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='add_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
