# Generated by Django 4.0.4 on 2022-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_equipement_hotel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement_hotel',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
