# Generated by Django 4.0.4 on 2022-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_categorieequipementhotel_equipement_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payement',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Carte de Crédit'), ('MOMO', 'Mobile Money'), ('P', 'Paypal')], default='CC', max_length=200),
        ),
    ]
