# Generated by Django 4.0.4 on 2022-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_tel_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='nuite',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
