# Generated by Django 4.0.4 on 2022-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_payement_token_reservation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
