# Generated by Django 4.0.4 on 2022-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_chambre_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('EC', 'En cours'), ('AN', 'Annulée'), ('T', 'Termineé'), ('P', 'Payée')], default='EC', max_length=200),
        ),
    ]
