# Generated by Django 4.0.4 on 2022-07-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte de Crédit'), ('momo', 'Mobile Money'), ('paypal', 'Paypal')], default='card', max_length=200),
        ),
    ]
