# Generated by Django 4.0.4 on 2022-08-17 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_chambre_description_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_hotel',
            name='image',
            field=models.ImageField(upload_to='images/hotel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
    ]
