# Generated by Django 4.0.4 on 2022-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_chambre_nuite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
