# Generated by Django 4.0.4 on 2022-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_chambre_slug_alter_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ville',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
