# Generated by Django 4.0.4 on 2022-07-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_payement_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='transaction_id',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
