# Generated by Django 4.0.4 on 2022-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_image_chambre_image_hotel_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
