# Generated by Django 4.0.4 on 2022-07-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('EC', 'En cours'), ('AN', 'Annulé'), ('P', 'Payé')], default='EC', max_length=200),
        ),
    ]
