# Generated by Django 4.0.4 on 2022-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_chambre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='tel_1',
            field=models.CharField(max_length=100),
        ),
    ]
