# Generated by Django 4.0.4 on 2022-06-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotel_tel_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
