# Generated by Django 4.0.4 on 2022-06-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_cartegorie_created_at_chambre_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartegorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='cartegorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='superficie',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chambre',
            old_name='nuite',
            new_name='overnight',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='adresse',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image_chambre',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image_hotel',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nom',
            new_name='name',
        ),
    ]
